[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["public/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/api/admin"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
